# Generated by Django 5.1.6 on 2025-03-25 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('secondname', models.CharField(max_length=100, verbose_name='secondname')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('phonenumber', models.IntegerField(verbose_name='phonenumber')),
            ],
            options={
                'db_table': 'divers',
            },
        ),
        migrations.CreateModel(
            name='owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('secondname', models.CharField(max_length=100, verbose_name='secondname')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('phonenumber', models.IntegerField(verbose_name='phonenumber')),
                ('car_reg_nop', models.TextField(max_length=100, verbose_name='car_reg_nop')),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_town', models.CharField(max_length=100, verbose_name='from_town_name')),
                ('To_town', models.CharField(max_length=100, verbose_name='to_town_name')),
                ('latatitude_from', models.FloatField(verbose_name='start_latitude')),
                ('longitude_from', models.FloatField(verbose_name='start_longitude')),
                ('assumed_distance', models.IntegerField(null=True, verbose_name='assumed distance')),
                ('vehicle_reg_nop', models.CharField(max_length=100, verbose_name='registration')),
                ('timestamps_start', models.BigIntegerField(verbose_name='car_reg_nop')),
                ('timestamps_arrival', models.BigIntegerField(null=True, verbose_name='arriva_time')),
                ('latitude_arrival', models.FloatField(null=True, verbose_name='arriva_lat')),
                ('long_arrival', models.FloatField(null=True, verbose_name='arrival_long')),
                ('speed', models.IntegerField(null=True, verbose_name='driver_speed')),
                ('date', models.TextField(verbose_name='to_date')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.drivers')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.owners')),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
