# Generated by Django 5.1.6 on 2025-03-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('secondname', models.CharField(max_length=100, verbose_name='secondname')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('companyname', models.CharField(max_length=100, verbose_name='password')),
                ('username', models.CharField(max_length=100, verbose_name='phonenumber')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='driversreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('Driver_id', models.IntegerField(verbose_name='Driver_id')),
                ('license_Type', models.CharField(max_length=100, verbose_name='license_Type')),
                ('Phonenumber', models.IntegerField(verbose_name='phonenumber')),
            ],
            options={
                'db_table': 'driversreg',
            },
        ),
        migrations.CreateModel(
            name='routemangt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100, verbose_name='vehicle_id')),
                ('start_location', models.CharField(max_length=100, verbose_name='start_location')),
                ('end_location', models.CharField(max_length=100, verbose_name=' end_location')),
                ('distance', models.IntegerField(verbose_name='distance')),
            ],
            options={
                'db_table': 'routemangt',
            },
        ),
        migrations.CreateModel(
            name='vehiclemaintance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100, verbose_name='vehicle_id')),
                ('last_service', models.CharField(max_length=100, verbose_name='last_service')),
                ('maintanance_type', models.CharField(max_length=100, verbose_name='maintanance_type')),
                ('next_scheduled_service', models.IntegerField(verbose_name='next_scheduled_service')),
            ],
            options={
                'db_table': 'vehiclemaintance',
            },
        ),
        migrations.CreateModel(
            name='vehicleregistations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_iD', models.IntegerField(verbose_name='vehicle_id')),
                ('make', models.CharField(max_length=100, verbose_name='make')),
                ('car_model', models.CharField(max_length=100, verbose_name='car_model')),
                ('Vin', models.IntegerField(verbose_name='vin')),
                ('license', models.IntegerField(verbose_name='licence')),
            ],
            options={
                'db_table': 'vehicleregistations',
            },
        ),
        migrations.RemoveField(
            model_name='records',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='records',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='drivers',
        ),
        migrations.DeleteModel(
            name='owners',
        ),
        migrations.DeleteModel(
            name='records',
        ),
    ]
