# Generated by Django 5.1.6 on 2025-03-27 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_admins_driversreg_routemangt_vehiclemaintance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driversreg',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
    ]
