# Generated by Django 5.1.6 on 2025-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_admins_email_alter_driversreg_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintance',
            name='next_scheduled_service',
            field=models.CharField(max_length=100, verbose_name='next_scheduled_service'),
        ),
    ]
