# Generated by Django 5.1.6 on 2025-03-28 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehiclemaintance_next_scheduled_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemangt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
