# Generated by Django 5.1.6 on 2025-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_routemangt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemangt',
            name='date',
            field=models.CharField(max_length=100, verbose_name='date'),
        ),
    ]
